# Key-Value Pairs
name: Prajyot Fulsundar
role: Cloud & Devops Engineer
overall_exep: 12 
automation: 9
experience_years: 3
learning: true

# Lists Using - (dash)
tools:
  - Docker
  - Jenkins
  - K8s
  - Terraform
  - Anisble
  - Playwright
  - Circle CI
  - ArgoCD

# Lists Using square brackets [ ] Inline format
hobbies: ["Trekking", "Playing Cricket", "Travel", "News"]
