apiVersion: v1
kind: Service
metadata:
  name: web-app-clusterip
spec:
  type: NodePort # 1. Change this from ClusterIP to NodePort
  selector:
    app: web-app # Make sure this matches the labels in app-deployment.yml
  ports:
    - protocol: TCP
      port: 80       # The port the service exposes inside the cluster
      targetPort: 80 # The port your actual container app runs on
      nodePort: 30080 # 2. Add this line to lock it onto port 30080